[project]
name = "qdrant-llamaindex-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.2.0",
    "llama-index",
    "llama-index-vector-stores-qdrant",
    "llama-index-embeddings-openai",
]
